version: "3.8"

services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    command: start --log trace --user ${DB_USER} --pass ${DB_PASS} file:/kami-surrealdb/mydatabase.db
    ports:
      - "8000:8000"
    volumes:
      - /kami-surrealdb:/kami-surrealdb
    env_file:
      - .env
    restart: "no"
