version: '3.9'

x-common-configs:
  &common-vars
  volumes:
    - ./airflow/dags:/opt/bitnami/airflow/dags
    - ./airflow/logs:/opt/bitnami/airflow/logs
    - ./airflow/plugins:/opt/bitnami/airflow/plugins
  networks:
    - all_connect

services:
  mongo:
    image: mongo:6.0.5
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - ./db/mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - all_connect
  postgresql:
    image: docker.io/bitnami/postgresql:15
    volumes:
      - ./db/postgres:/bitnami/postgresql
    environment:
      - POSTGRESQL_DATABASE=bitnami_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1
    networks:
      - all_connect
  redis:
    image: docker.io/bitnami/redis:7.0
    volumes:
      - ./db/redis:/bitnami'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - all_connect
  airflow-scheduler:
    <<: *common-vars
    image: docker.io/bitnami/airflow-scheduler:2
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
  airflow-worker:
    <<: *common-vars
    image: docker.io/bitnami/airflow-worker:2
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
  airflow:
    <<: *common-vars
    image: docker.io/bitnami/airflow:2
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
    ports:
      - '8080:8080'
volumes:
  postgres-db-volume:
  redis_data:
networks:
  all_connect:
    external: true
    name: all_connect
