version: "3.9"
services:
  mongo:
    image: mongo:6.0.5
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - ./db/mongo:/data/db
    ports:
      - "27017:27017"
