apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: postgresql-data-claim # Sets name of PV
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce # Sets read and write access
  resources:
    requests:
      storage: 100Gi # Sets volume size
